# run
setting: 'sehstr'

# wandb
wandb_mode: 'online'  # 'online', 'disabled'
wandb_project: 'subgfn'
wandb_entity: 'rb-aiml'

# model learning
lr_z: 1.0e-3
lr_policy: 1.0e-5
clip_policy_logit_min: -50.0
clip_policy_logit_max: 50.0
clip_grad_norm: 10.0
model: 'sub' # choices=['sub', 'maxent', 'random', 'tb']
guide: 'substructure' # choices=['substructure', 'uniform']
init_logz: True
# CAREFUL - guide_scores_back_policy_traj can have high variance in 
# training losses because trajectorie sampled under back policy can have
# extremely low logp under guide 
# choices=['guide_scores_back_policy_traj', 'guide_resamples_traj'])
offline_style: 'guide_resamples_traj' 
offline_select: 'biased'

sa_or_ssr: 'sa'
# sa_or_ssr: 'ssr'

# model architecture
# inp_dim is specified by mdp
ssr_encoder_hid_dim: 1024
ssr_encoder_n_layers: 1
ssr_embed_dim: 1024
ssr_scorer_hid_dim: 1024
ssr_scorer_n_layers: 1
sa_hid_dim: 1024
sa_n_layers: 2

# trainer
num_active_learning_rounds: 2000
num_samples_per_online_batch: 16
num_samples_per_offline_batch: 16

num_steps_per_batch: 1
num_online_batches_per_round: 1
num_offline_batches_per_round: 1
target_mix_backpolicy_weight: 0.5

# policy
explore_epsilon: 0.05

# guide
parallelize: True
num_guide_workers: 30

# experiment
replicate: 0
saved_models_dir: 'saved_models/'
save_every_x_active_rounds: 100

# monitor
monitor_num_samples: 128
monitor_fast_every: 10
monitor_slow_every: 200

# reward
train_inverse_temperature: 3.0
scale_reward_max: 10
drop_reward_min: 1e-3
guide_sampling_temperature: 1.0

# experiment-specific settings
blocks_file: datasets/sehstr/block_18.json
forced_stop_len: 6
